Add more configuration options for MobileReleaseLogger
Khan/wonder-stuff pull request #754
Opened 2023-06-06 22:14 UTC by jlauzy

## Summary:
- Just adding more configurations options.

Issue: XXX-XXXX

## Test plan:

2023-06-07 13:19 UTC, jeresig approved these changes

2023-06-07 18:17 UTC, somewhatabstract requested changes
Looks good; needs a changeset to be added before you can land this. I suspect this would be a `minor` update since it is adding new things but code using the old API would still work. Is that correct? If old code would break as soon as updating to this, then I think it would need to be a `major` update.

2023-06-08 17:18 UTC, jlauzy commented
> Looks good; needs a changeset to be added before you can land this. I suspect this would be a `minor` update since it is adding new things but code using the old API would still work. Is that correct? If old code would break as soon as updating to this, then I think it would need to be a `major` update.

@somewhatabstract added the changeset! Going to make a minor instead of major bump because no one was using the logger class since it was broken 😅

2023-06-08 17:22 UTC, somewhatabstract approved these changes

2023-06-08 17:29 UTC, merged